### ISSUE TITLE
Hibernation issue

### ISSUE THREAD

**Issue by GaradaK7** [catright/Wale#10]
After resume from hibernation, Wale need to be restarted to continue working property.

Greetings and thanks for the program.

**Comment by catright** [comment]
Thank you very much for your report. I'll take a look very soon.

**Comment by GaradaK7** [comment]
I'm sorry but seems that hibernation is not the real or the only cause of the issue.
I think it can be another audio software (EarTrumpet) and/or remote (RDP) conections to the PC.
I'm going to make some tests to be sure of the cause of the problems.
Thanks.

**Comment by GaradaK7** [comment]
OK, confirmed.
Hibernate is not affecting Wale, RDP sessions is what making Wale irresponsibly (crashing or not detecting software playing sounds)
It doesn't matter how you config how RDP plays sound (play on remote, play on this or don't play)
I'm sorry if I wasted your time.

**Comment by catright** [comment]
I'm very appreciate for your great help.
I have known about the app crash when audio device is changed, but still finding how to fix this.
And I totally missed this problem is occurred when remote session is established which may also change audio device settings or its states that causes the crash.
I think remote session issue would be fixed when I find the way to fix the audio device issue.

**Comment by mikeloeven** [comment]
I am unsure is this is related but It may be the result of the computer automatically switching the In use audio device. I frequently have WALE on my laptop crash when loading a full screen game because this changes the display mode. As my stereo is connected to the TV via HDMI the crash appears to be caused by the brief period when the laptop switches from Display Audio out to the internal realtek speakers and than back to Display Audio device when the resolution has changed. Issue also occurs when the TV is turned off even if the computer remains awake and running services in the background.

**Comment by catright** [comment]
Display changes can cause audio device changes, so it may related this issue.
Please try [0.6.6](https://github.com/catright/Wale/blob/master/WaleSetup_0.6.6.msi)
I've changed handling of audio device changing.

**Comment by mikeloeven** [comment]
0.6.6 Still seems to have intermittent crashing issues trigger still seems to be when the TV is turned off and the program looses its connection to HDMI Audio. 
[WaleLog-20201204-123235.txt](https://github.com/catright/Wale/files/5647641/WaleLog-20201204-123235.txt)
[WaleLog-20201205-130638.txt](https://github.com/catright/Wale/files/5647642/WaleLog-20201205-130638.txt)

**Comment by catright** [comment]
This problem continued on #22
