### ISSUE TITLE
Optimal settings? (Question)

### ISSUE THREAD

**Issue by Lichtenshtein** [catright/Wale#11]
Often, programs or games launched for the first time are too loud. Wale seems very useful to me in this problem. I did not find anything else to deal with this problem on Windows, and my drivers do not provide the necessary options that can help. But my question is, can I just limit the volume of all new applications with this program, say, 50%, but without dynamically changing the volume? This is very unpleasant when listening to music due to the constant abrupt change in the volume of songs. At this moment, Wale loads the 4-core processor by 5-8% (this is not very much, but it seems to me noticeable).

**Comment by catright** [comment]
I've recognized about that inconveniency on listening music or watching movie which you're said. But it was not so critical for me. So I've let it be. And now, someone is appeared who's concerning about it. Yeah. Why not? I'll make it for you.
Thank you for a good opinion and using Wale.

**Comment by catright** [comment]
I've added Static mode on config tab(F3).
You can use this mode to set all apps' volume to fixed level.
And in this mode, Wale's audio controller will work along UIUpdateInterval(100ms) rather than AutoControlInterval(15ms).
Hence Cpu usage would be little bit lower than normal mode.
If you feel the cpu usage is still too high. Please let me know. I'll gladly find a new way.

However, Static mode is not fit to concept of Wale, which means, Wale can not normalize the output sound levels.
You might be heard big or small sounds again.

If you want to try first just download(_right click > save link as_) [v0.5.14(msi)](https://github.com/catright/Wale/blob/master/WaleSetup_0.5.14.msi) or [v0.5.14(zip)](https://github.com/catright/Wale/blob/master/WalePortable_0.5.14.zip). But this version is barely tested, so it's possible that Wale behaves something strange.

I'll release this version after few days of test use by myself.

**Comment by Lichtenshtein** [comment]
> Static mode 

This is exactly what i wanted. Everything seems to be working fine

> Cpu usage would be little bit lower than normal mode

It is around ~1% now, that's awesome

> You might be heard big or small sounds again.

I will continue to test if i encounter any problems, i will try to inform

**Comment by Lichtenshtein** [comment]
I created a [topic](https://forum.ru-board.com/topic.cgi?forum=5&topic=50485) about Wale in one of the oldest russian software forums. I hope this helps more people to find out about your program.

**Comment by catright** [comment]
I thank you for your great help.
Please open a new issue freely when you got another problem.
Issue closed
