### ISSUE TITLE
Equalizer APO in combination with Wale possible?

### ISSUE THREAD

**Issue by CHEF-KOCH** [catright/Wale#5]
Hello, first of all, thanks for the project here, it really looks interesting! 

Since my audio knowledge is limited I ask directly if [Equalizer APO](https://sourceforge.net/projects/equalizerapo/) (I use [Peace](https://sourceforge.net/projects/peace-equalizer-apo-extension/)) can work together with Wale? Since Equalizer APO works on a per-device level I'm not sure if this will affect Wale or the audio latency, which is my main concern. 

My main goal would be that I can separate specific applications like e.g. Chrome/Firefox etc from the microphone? And is it recommended to combine them, it would be cool if you can comment on this, which might also help others with the same question. 

Thanks for your feedback and time.

**Comment by catright** [comment]
_Firstly_, i thanks for your interesting on my project.

In fact, I'm not an audio professional nor a pro developer. I'm trying to import spectral analyzing to adapt to human hearing but i couldn't succeed still. Until now, i only know that timing accuracy of .Net application which is not audio driver level is not sufficient for real time analyzing. I guess it's possible to apply an equalizer filter in some other way whilst i need to study more for that. I think its affect to latency or processing power wouldn't be much big. I'm sorry for that i couldn't let you know a proper answer. 

_For your goal_, It would be needed to make some other things to control input sessions, because Wale only controls output sessions for now. It will be needed to capture input sounds, apply EQ filter or volume control, redirect to output device. This may cause a little latency on application level.

I need to apply audio driver for precise control. But it would be later.

On the other hand, I'm very glad to your participation. If you don't mind, I'll invite you to Wale and make another branch for EQ.
